services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - .:/app
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis-test
    ports:
      - "6379:6379"
    restart: unless-stopped
